[project]
name = "python-challenges"
version = "0.1.0"
description = "Programming challenges written in the Python programming language."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["pytest>=8.3.3", "ruff>=0.7.1"]
